### ISSUE TITLE
Footer is overlapping the content area

### ISSUE THREAD

**Issue by aditionkar** [SRM-IST-KTR/githubsrmv2#125]
In Our story and Events page footer is overlapping the content area

![Screenshot 2024-11-15 224724](https://github.com/user-attachments/assets/8e90f893-40f0-4656-af8e-83400c972779)

![Screenshot 2024-11-15 224742](https://github.com/user-attachments/assets/b28db0ae-a305-44e7-923a-c428a494fe88)

**Comment by Sameer01-01** [comment]
i can solve it

## Laptop
![Screenshot 2024-11-19 041926](https://github.com/user-attachments/assets/5e3d8acf-e1f8-4550-9b1c-c50bf47a9f4c)

![Screenshot 2024-11-19 042114](https://github.com/user-attachments/assets/6f080c00-bbf2-46d8-8795-7542d6c67516)

## Mobile  
Note :- The white line won't be there on deployment for mobile devices

![Screenshot 2024-11-19 041950](https://github.com/user-attachments/assets/95dde5fe-c553-466c-a7e5-ecd4e28d95ab)

![Screenshot 2024-11-19 042102](https://github.com/user-attachments/assets/dfdffdd1-cd8e-4824-b4e8-fc6d78a65895)
