### ISSUE TITLE
Incorrect span of hero section on home page

### ISSUE THREAD

**Issue by UtkarshJaiswal1406** [SRM-IST-KTR/githubsrmv2#83]
## The hero section isn't spanning the entire page
The home screen should be completely covered by the hero section. The About Us box should only be visible after scrolling down a bit instead of popping up awkwardly at first load. Please fix it

![chrome_sLlBWHVPeB](https://github.com/user-attachments/assets/523a97b2-a5d9-4ce5-9181-863cb810a85c)

**Comment by sahaj24** [comment]
@UtkarshJaiswal1406  I can Fix that

**Comment by sahaj24** [comment]
![Screenshot 2024-10-23 234238](https://github.com/user-attachments/assets/784c5d00-c3f0-4f94-8135-d96957bc3255)

**Comment by djdiptayan1** [comment]
are you using windows or mac or linux? if on windows, please check your resolution scaling, it should be 100% then check the site again. same applies for mac and linux. ping me back

**Comment by sahaj24** [comment]
I am using Windows and Yes my Windows resolution is 100%.
