### ISSUE TITLE
Recruitment section still visible

### ISSUE THREAD

**Issue by UtkarshJaiswal1406** [SRM-IST-KTR/githubsrmv2#85]
Since the recruitments are over for this year, this section should be cleanly removed from the website along with its elements (for eg, the navbar entry). Please fix

![chrome_4jBKa3nyDA](https://github.com/user-attachments/assets/945ff5b7-83d9-4ae2-8c09-a43887f3b4d4)

**Comment by Sameer01-01** [comment]
i can do this


Navbar after removal
![Screenshot 2024-10-24 221711](https://github.com/user-attachments/assets/2ed79c34-1b64-4b81-9fde-5a5a7a4dce59)

File structure
![Screenshot 2024-10-24 221645](https://github.com/user-attachments/assets/79b757b1-095c-4a79-b808-9977e37086cd)

**Comment by Jaksh-jain** [comment]
Is this task assigned to sameer bhai or it is free to allstill now

**Comment by UtkarshJaiswal1406** [comment]
PR Assigned to @Sameer01-01
