### ISSUE TITLE
Transition but in FAQ forms

### ISSUE THREAD

**Issue by UtkarshJaiswal1406** [SRM-IST-KTR/githubsrmv2#87]
The corners of the the FAQ questions turn in sharp corners for a moment when closed before going back to their round shape. Fix this 

https://github.com/user-attachments/assets/9ed1f4a6-5ac9-4d46-977e-07bc75580a3d

**Comment by sahaj24** [comment]
@UtkarshJaiswal1406 I can do this.

https://github.com/user-attachments/assets/9a374b6a-3b2a-489a-bd02-0833a50a42a0

**Comment by djdiptayan1** [comment]
its opening all of a sudden, make it smooth like roll down something like that

**Comment by sahaj24** [comment]
fixed
