### ISSUE TITLE
Centre footer in mobile View

### ISSUE THREAD

**Issue by djdiptayan1** [SRM-IST-KTR/githubsrmv2#88]
The footer content needs to be centered and justified. the social buttons and "Created By GCSRM Team 🐐" needs to be centered.
Also center the logo and adderss

<img width="375" alt="Screenshot 2024-10-18 at 11 35 01 PM" src="https://github.com/user-attachments/assets/039a7db0-c949-468b-b428-3abd0a87f714">

**Comment by Sameer01-01** [comment]
I can fix this 

before 
![Screenshot 2024-10-23 120842](https://github.com/user-attachments/assets/675ea5ea-1290-4976-a193-21e6919f207c)


after

![Screenshot 2024-10-23 120911](https://github.com/user-attachments/assets/2367bf47-a4e0-4669-a426-c3a0f88279ad)

**Comment by Sameer01-01** [comment]
I can fix this issue.


# before 
![Screenshot 2024-10-23 120842](https://github.com/user-attachments/assets/95f7ebf4-c560-4f8b-bfac-c585c48c661b)

# After
![Screenshot 2024-10-23 120911](https://github.com/user-attachments/assets/d2730bd2-77e9-4abc-82a9-f77cf0c77577)

**Comment by djdiptayan1** [comment]
Sure. text in discord. team lead will assign it to you @Sameer01-01

**Comment by UtkarshJaiswal1406** [comment]
@Sameer01-01 keep in mind that its still off center from the page's perspective because the 'scroll to top' button is messing with the alignment on the right side.
also that white line at the bottom shouldnt be there.
Keep these issues in mind while working on this

**Comment by Sameer01-01** [comment]
> Sure. text in discord. team lead will assign it to you @Sameer01-01

ok..should i text in the technical discussion channel or somewhere else??

**Comment by UtkarshJaiswal1406** [comment]
> ok..should i text in the technical discussion channel or somewhere else??

technical discussion

**Comment by Sameer01-01** [comment]
> @Sameer01-01 keep in mind that its still off center from the page's perspective because the 'scroll to top' button is messing with the alignment on the right side. also that white line at the bottom shouldnt be there. Keep these issues in mind while working on this

ok bhiaya...the white line is just visible in chrome when i view it in different phones using chrome dev tools, it won't be there in the deployed website.

the scroll button is fixed in the webpage...should i move the footer a little upwards so that it will be centered and also it wont look odd with respect to the scroll button??

**Comment by UtkarshJaiswal1406** [comment]
> ok bhiaya...the white line is just visible in chrome when i view it in different phones using chrome dev tools, it won't be there in the deployed website.
> 
> the scroll button is fixed in the webpage...should i move the footer a little upwards so that it will be centered and also it wont look odd with respect to the scroll button??

scroll button is messing with the horizontal alignment. I don't see how moving the footer up would help. Try something else

**Comment by UtkarshJaiswal1406** [comment]
I'm assigning this issue to you. Create a new branch and experiment

Add me, diptayan and anushka as the reviewers whenever your decide to open a PR

**Comment by Sameer01-01** [comment]
> I'm assigning this issue to you. Create a new branch and experiment

ok bhaiya..i will do that.

**Comment by Sameer01-01** [comment]
i have done a change...the scroll button will be visible till contact us form and after that it will be hidden...by doing this the footer will be centered...is this ok??

## footer part
![Screenshot 2024-10-23 162730](https://github.com/user-attachments/assets/8c7402ce-c097-4953-8f4a-fe18c0b88754)


# contact us part
![Screenshot 2024-10-23 162744](https://github.com/user-attachments/assets/0c17a4b4-a686-4859-a1c6-c6d78a82b80e)

**Comment by djdiptayan1** [comment]
check the footer part once, its not properly centered. rest is good in my opinion.

**Comment by Sameer01-01** [comment]
> check the footer part once, its not properly centered. rest is good in my opinion.

ok..is this fine??

![Screenshot 2024-10-23 170051](https://github.com/user-attachments/assets/97b39609-6141-441e-a0b5-bdd22cde5b6a)

**Comment by djdiptayan1** [comment]
desktop view should not be affected.

**Comment by Sameer01-01** [comment]
this is the desktop view

![Screenshot 2024-10-23 195253](https://github.com/user-attachments/assets/7ad05376-4a12-4a48-85dc-5e65cc23faf2)
