### ISSUE TITLE
Incorrect animation on the contact form

### ISSUE THREAD

**Issue by UtkarshJaiswal1406** [SRM-IST-KTR/githubsrmv2#90]
The hover animation on the contact form both on the Home page and on the Contact page is different from the rest of the hover animations as shown in the clip below. Its very choppy. Fix it

https://github.com/user-attachments/assets/c2050349-e814-44fd-bd47-f013f046d9c4

**Comment by sahaj24** [comment]
I can do that

**Comment by sahaj24** [comment]
https://github.com/user-attachments/assets/7018f2d9-3289-4744-a262-4ef26ef9d346
