### ISSUE TITLE
Dynamic Sponsor's Display

### ISSUE THREAD

**Issue by djdiptayan1** [SRM-IST-KTR/githubsrmv2#93]
Fetch Sponsor name and logo  from database and display them in the website, currently its a JSON. This will help us to add sponsors without changing any code.

**Comment by ronakjain2012** [comment]
Hi, Could I take this ?

**Comment by ghost** [comment]
I would like to work on this.

**Comment by UtkarshJaiswal1406** [comment]
> I would like to work on this.

Okayy, assigning it to you
